version: "3.3"
services: 
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: 53nH48aNc0
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
  api:
    image: "bitnami/laravel"
    container_name: laravel-container
    restart: always
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db